/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class CainActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  async _preCreate(data, options, user) {
    await super._preCreate(data, options, user);

    // Set default prototype token settings for all actor types
    const prototypeToken = {
      actorLink: true,  // Link actor data
      texture: {
        src: data.img || "icons/svg/mystery-man.svg"  // Use actor image or default
      }
    };

    this.updateSource({ prototypeToken });
  }

  async _onCreate(data, options, userid) {
    await super._onCreate(data, options, userid);

    console.log('created!')
    // Register any relevant apps. These will re-render whenever this actor updates
    if (this.type === 'character') {
      this.apps['pathos-tracker'] = ui.pathosTracker;
      ui.pathosTracker.render({ force: true });
    }
  }

  _onDelete(options, userId) {
    // If character, unlink pathos tracker so it doesn't get deleted
    if (this.type === 'character') {
      delete this.apps['pathos-tracker'];
    }
    super._onDelete(options, userId);

    // force a re-render of the pathos element
    ui.pathosTracker.render({ force: true });
  }

  /** @override */
  async _preUpdate(changed, options, user) {
    await super._preUpdate(changed, options, user);

    // If the actor image is being updated, also update the prototype token image
    if (changed.img && !changed.prototypeToken?.texture?.src) {
      this.updateSource({
        "prototypeToken.texture.src": changed.img
      });
    }
  }

  async _onUpdate(changed, options, user) {
    super._onUpdate(changed, options, user);
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't 
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.cain || {};
  }

  /**
   * 
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic 
   * approach is useful when you have actors & items that share a parent Document, 
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...this.system.getRollData?.() ?? null };
  }

  /**
   * Convert the actor document to a plain object.
   * 
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   * 
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = {...this};

    // Simplify system data.
    result.system = this.system.toPlainObject?.() ?? {...this.system};

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    return result;
  }

}
